#!/usr/bin/env bash

comments="# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.
"

# Create a new AUTHORS file with the contributor list
echo "$comments" > AUTHORS

# Get a list of all contributors from Git history
git log --format='%aN <%aE>' | sort -u >> AUTHORS
